"""Public API for spectral feature configuration, layouts, and extraction."""

from .config import (
    DEFAULT_SPECTRAL_ATTENTION_GRANULARITY,
    DEFAULT_SPECTRAL_ENTRYWISE_DELTA_MODE,
    DEFAULT_SPECTRAL_FEATURES,
    DEFAULT_SPECTRAL_MOMENT_SOURCE,
    DEFAULT_SPECTRAL_QV_SUM_MODE,
    SPECTRAL_EXTRACTOR_VERSION,
    SUPPORTED_SPECTRAL_ATTENTION_GRANULARITIES,
    SUPPORTED_SPECTRAL_ENTRYWISE_DELTA_MODES,
    SUPPORTED_SPECTRAL_FEATURES,
    SUPPORTED_SPECTRAL_MOMENT_SOURCES,
    SUPPORTED_SPECTRAL_QV_SUM_MODES,
    expand_spectral_feature_names,
    resolve_spectral_attention_granularity,
    resolve_spectral_entrywise_delta_mode,
    resolve_spectral_features,
    resolve_spectral_moment_source,
    resolve_spectral_qv_sum_mode,
    spectral_extractor_params,
)
from .extraction import extract_spectral_features
from .layout import (
    AttentionHeadLayout,
    QvSumSpec,
    build_qv_sum_specs,
    build_spectral_feature_names,
    feature_group_for_spectral_feature_name,
    provenance_source_feature_group,
    rank_normalized_feature_group,
)
from .metadata import (
    feature_block_name,
    layer_identifier_for_block_name,
    ordered_block_names_from_feature_names,
    sanitize_spectral_metadata,
    spectral_block_lora_dims_by_block,
    summarize_schema_layout,
)

__all__ = [
    "AttentionHeadLayout",
    "DEFAULT_SPECTRAL_ATTENTION_GRANULARITY",
    "DEFAULT_SPECTRAL_ENTRYWISE_DELTA_MODE",
    "DEFAULT_SPECTRAL_FEATURES",
    "DEFAULT_SPECTRAL_MOMENT_SOURCE",
    "DEFAULT_SPECTRAL_QV_SUM_MODE",
    "QvSumSpec",
    "SPECTRAL_EXTRACTOR_VERSION",
    "SUPPORTED_SPECTRAL_ATTENTION_GRANULARITIES",
    "SUPPORTED_SPECTRAL_ENTRYWISE_DELTA_MODES",
    "SUPPORTED_SPECTRAL_FEATURES",
    "SUPPORTED_SPECTRAL_MOMENT_SOURCES",
    "SUPPORTED_SPECTRAL_QV_SUM_MODES",
    "build_qv_sum_specs",
    "build_spectral_feature_names",
    "expand_spectral_feature_names",
    "extract_spectral_features",
    "feature_block_name",
    "feature_group_for_spectral_feature_name",
    "layer_identifier_for_block_name",
    "ordered_block_names_from_feature_names",
    "provenance_source_feature_group",
    "rank_normalized_feature_group",
    "resolve_spectral_attention_granularity",
    "resolve_spectral_entrywise_delta_mode",
    "resolve_spectral_features",
    "resolve_spectral_moment_source",
    "resolve_spectral_qv_sum_mode",
    "sanitize_spectral_metadata",
    "spectral_block_lora_dims_by_block",
    "spectral_extractor_params",
    "summarize_schema_layout",
]
